CREATE TRIGGER IF NOT EXISTS set_status_after_insert
    AFTER INSERT ON REGISTER
    FOR EACH ROW
    BEGIN
        UPDATE REGISTER SET STATUS = 'Submitted' WHERE APPLICATION_NO = NEW.APPLICATION_NO;
    END;